import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/mining';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    flex: 1,
    padding: 16,
    justifyContent: 'center',
    zIndex: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.cyan,
    textAlign: 'center',
    marginBottom: 32,
  },
  miningAnimationContainer: {
    alignItems: 'center',
    marginBottom: 32,
  },
  pickaxeContainer: {
    position: 'relative',
  },
  pickaxeIcon: {
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: COLORS.orange,
    borderWidth: 4,
    borderColor: COLORS.orangeLight,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  pickaxeText: {
    fontSize: 64,
  },
  infoCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 24,
    padding: 24,
    borderWidth: 4,
    borderColor: COLORS.cyan,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  infoIcon: {
    fontSize: 24,
    marginRight: 8,
  },
  infoLabel: {
    fontSize: 14,
    color: COLORS.textLight,
    fontWeight: '600',
  },
  timeText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: 24,
  },
  progressContainer: {
    marginBottom: 24,
  },
  progressBarBackground: {
    width: '100%',
    height: 24,
    backgroundColor: COLORS.darkCard,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: COLORS.slate,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: COLORS.cyan,
    borderRadius: 12,
  },
  progressText: {
    fontSize: 14,
    color: COLORS.textLight,
    textAlign: 'center',
    marginTop: 8,
    fontWeight: '600',
  },
  tokensCard: {
    backgroundColor: COLORS.darkCard,
    borderRadius: 16,
    padding: 16,
    borderWidth: 2,
    borderColor: COLORS.orange,
  },
  tokensHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  tokensIcon: {
    fontSize: 24,
    marginRight: 8,
  },
  tokensLabel: {
    fontSize: 14,
    color: COLORS.textLight,
    fontWeight: '600',
  },
  tokensAmount: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.text,
    textAlign: 'center',
  },
  statsCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 16,
    padding: 16,
    borderWidth: 4,
    borderColor: COLORS.orange,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  statItem: {
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.textLight,
    marginBottom: 4,
    fontWeight: '600',
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  statHint: {
    marginTop: 4,
    fontSize: 11,
    color: COLORS.textLight,
  },
  cancelButton: {
    backgroundColor: COLORS.darkCard,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderWidth: 4,
    borderColor: COLORS.slate,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonIcon: {
    fontSize: 20,
    color: COLORS.textLight,
    marginRight: 8,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.textLight,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 20,
    padding: 20,
    width: '90%',
    maxHeight: '85%',
    borderWidth: 4,
    borderColor: 'rgba(44, 255, 233, 1)',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 14,
    color: COLORS.textLight,
    marginBottom: 20,
    textAlign: 'center',
  },
  currentMultiplierInfo: {
    backgroundColor: COLORS.darkCard,
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    alignItems: 'center',
  },
  infoValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.bitcoin,
  },
  multiplierOptions: {
    marginBottom: 20,
  },
  multiplierOption: {
    backgroundColor: COLORS.darkCard,
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
  },
  multiplierOptionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  multiplierOptionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  multiplierOptionRate: {
    fontSize: 14,
    color: COLORS.textLight,
    marginBottom: 5,
  },
  multiplierBoost: {
    fontSize: 12,
    color: COLORS.success,
    fontWeight: '600',
  },
  upgradeNote: {
    fontSize: 11,
    color: COLORS.textLight,
    marginTop: 8,
    fontStyle: 'italic',
  },
  maxMultiplierMessage: {
    backgroundColor: COLORS.success,
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  maxMultiplierText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: 5,
  },
  maxMultiplierSubtext: {
    fontSize: 14,
    color: COLORS.text,
    opacity: 0.9,
  },
  adBadge: {
    backgroundColor: COLORS.primary,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  adBadgeText: {
    color: COLORS.text,
    fontSize: 11,
    fontWeight: 'bold',
  },
  modalCloseButton: {
    backgroundColor: COLORS.darkCard,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  modalCloseButtonText: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: 'bold',
  },
  adLoadingOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  adLoadingContent: {
    backgroundColor: COLORS.cardBg,
    padding: 30,
    borderRadius: 15,
    alignItems: 'center',
  },
  adLoadingText: {
    color: COLORS.text,
    fontSize: 16,
    marginTop: 15,
    fontWeight: 'bold',
  },
  adLoadingSubtext: {
    color: COLORS.textLight,
    fontSize: 14,
    marginTop: 5,
  },
  homeButton: {
    backgroundColor: COLORS.cyan,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderWidth: 4,
    borderColor: COLORS.cyanLight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  homeButtonIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  homeButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.darkCard,
  },
});

export default styles;